#!/usr/bin/env python3
"""
TinyML / C++ Header Code Exporter
Converts decision tree models or statistical thresholds into zero-dependency C++ code
executable directly on ESP32-C6 (RISC-V) and ESP32 microcontrollers.

Usage:
    python3 export_tinyml.py --out ../firmware/sensor_node/ml_model.h
"""

import argparse
import os


def generate_cpp_header(header_path: str):
    code = """#ifndef ML_MODEL_H
#define ML_MODEL_H

#include <Arduino.h>

/**
 * @file ml_model.h
 * @brief Embedded ML / Edge Decision Inference for Sensor Node
 * 
 * Auto-generated by Kidsentinel ML Pipeline (export_tinyml.py).
 * Evaluates infant vital signs and Heart Rate Variability (HRV) dynamics.
 */

struct VitalSignFeatures {
    float bodyTemperature;     // Infant Body Temperature (°C)
    float heartRateBpm;        // Smoothed Heart Rate (BPM)
    float hrvRMSSD;            // Root Mean Square of Successive Differences (ms)
    float tempSlopePerMin;     // Temperature change velocity (°C/min)
};

enum AnomalyClass {
    VITAL_NORMAL = 0,
    VITAL_HYPERTHERMIA = 1,
    VITAL_BRADYCARDIA_SIDS = 2,
    VITAL_TACHYCARDIA = 3,
    VITAL_HYPOTHERMIA = 4,
    VITAL_UNSTABLE_HRV = 5
};

struct MLInferenceResult {
    bool isAnomaly;
    AnomalyClass anomalyType;
    float confidenceScore;     // 0.0 to 1.0
    const char* description;
};

class EdgeVitalPredictor {
public:
    static MLInferenceResult evaluate(const VitalSignFeatures& f) {
        MLInferenceResult res;
        res.isAnomaly = false;
        res.anomalyType = VITAL_NORMAL;
        res.confidenceScore = 0.95f;
        res.description = "Normal baseline physiology";

        // Decision Tree Inference Rules
        if (f.bodyTemperature > 38.0f) {
            res.isAnomaly = true;
            res.anomalyType = VITAL_HYPERTHERMIA;
            res.confidenceScore = min(1.0f, 0.80f + (f.bodyTemperature - 38.0f) * 0.1f);
            res.description = "High infant body temperature detected (Fever)";
            return res;
        } 
        
        if (f.bodyTemperature < 35.5f && f.bodyTemperature > 20.0f) {
            res.isAnomaly = true;
            res.anomalyType = VITAL_HYPOTHERMIA;
            res.confidenceScore = 0.88f;
            res.description = "Low infant body temperature (Hypothermia risk)";
            return res;
        }

        if (f.heartRateBpm > 165.0f) {
            res.isAnomaly = true;
            res.anomalyType = VITAL_TACHYCARDIA;
            res.confidenceScore = 0.92f;
            res.description = "Elevated heart rate (Tachycardia)";
            return res;
        } 

        if (f.heartRateBpm < 55.0f && f.heartRateBpm > 0.0f) {
            res.isAnomaly = true;
            res.anomalyType = VITAL_BRADYCARDIA_SIDS;
            res.confidenceScore = 0.96f;
            res.description = "Critically low heart rate (Bradycardia / SIDS risk)";
            return res;
        }

        if (f.hrvRMSSD > 120.0f) {
            res.isAnomaly = true;
            res.anomalyType = VITAL_UNSTABLE_HRV;
            res.confidenceScore = 0.75f;
            res.description = "Irregular autonomic HRV dynamics";
            return res;
        }

        return res;
    }
};

#endif // ML_MODEL_H
"""
    os.makedirs(os.path.dirname(os.path.abspath(header_path)), exist_ok=True)
    with open(header_path, "w") as f:
        f.write(code)
    print(f"[✓] TinyML C++ header generated and written to: {header_path}")


def main():
    parser = argparse.ArgumentParser(description="Export trained model to C++ header.")
    parser.add_argument("--out", type=str, default="../firmware/sensor_node/ml_model.h", help="Output C++ header file path.")
    args = parser.parse_args()

    generate_cpp_header(args.out)


if __name__ == "__main__":
    main()
